apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: porter-system
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      hostNetwork: true
      nodeSelector:
        dedicated: master
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        readinessProbe:
          httpGet:
            path: /hello
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # - name: SECRET_NAME
          #   value: $(WEBHOOK_SECRET_NAME)
        volumeMounts:
        - name: config-bgp
          mountPath: /etc/config
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        # ports:
        # - containerPort: 9876
        #   name: webhook-server
        #   protocol: TCP
        # volumeMounts:
        # - mountPath: /tmp/cert
        #   name: cert
        #   readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      # - name: cert
      #   secret:
      #     defaultMode: 420
      #     secretName: webhook-server-secret
      - name: config-bgp
        configMap:
          name: bgp-cfg

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: system

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: porter-service-account