apiVersion: v1
kind: Service
metadata:
  name: porter-admission
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: 443
  selector:
    control-plane: porter-manager
    app: porter-manager