apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: porter-admission
webhooks:
  - name: validate.eip.network.kubesphere.io
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - network.kubesphere.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - eips
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        namespace: porter-system
        name: porter-admission
        path: /validate-network-kubesphere-io-v1alpha2-eip