apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: porter-agent
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: magicsong/porter-agent:fca0c6a4
        name: porter-agent
