apiVersion: apps/v1
kind: Deployment
metadata:
  name: porter-manager
  namespace: system
  labels:
    control-plane: porter-manager
    app: porter-manager
spec:
  selector:
    matchLabels:
      control-plane: porter-manager
      app: porter-manager
  template:
    metadata:
      labels:
        control-plane: porter-manager
        app: porter-manager
    spec:
      hostNetwork: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - porter-manager
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      # cloud controller manages should be able to run on masters
      - key: "node-role.kubernetes.io/master"
        effect: NoSchedule
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        readinessProbe:
          httpGet:
            path: /hello
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # - name: SECRET_NAME
          #   value: $(WEBHOOK_SECRET_NAME)
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        # ports:
        # - containerPort: 9876
        #   name: webhook-server
        #   protocol: TCP
        # volumeMounts:
        # - mountPath: /tmp/cert
        #   name: cert
        #   readOnly: true
      terminationGracePeriodSeconds: 10

