apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: porter-agent
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: kubespheredev/porter-agent:bc7c58a5
          name: porter-agent
          imagePullPolicy: Always
