apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: porter-agent
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: kubespheredev/porter-agent:356abaf4
        name: porter-agent
        imagePullPolicy: Always
