apiVersion: apps/v1
kind: Deployment
metadata:
  name: porter-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: kubespheredev/porter:bc7c58a5
        name: manager
        imagePullPolicy: Always
