
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: eips.network.kubesphere.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.address
    name: cidr
    type: string
  - JSONPath: .status.usage
    name: usage
    type: integer
  - JSONPath: .status.poolSize
    name: total
    type: integer
  group: network.kubesphere.io
  names:
    categories:
    - ksnet
    kind: Eip
    plural: eips
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Eip is the Schema for the eips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EipSpec defines the desired state of EIP
          properties:
            address:
              pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}((\/([0-9]|[1-2][0-9]|3[0-2]))|(\-([0-9]{1,3}\.){3}[0-9]{1,3}))?$
              type: string
            disable:
              type: boolean
            usingKnownIPs:
              type: boolean
          type: object
        status:
          description: EipStatus defines the observed state of EIP
          properties:
            occupied:
              type: boolean
            poolSize:
              type: integer
            usage:
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
